# Generated by Django 5.1.4 on 2025-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('percentile', models.FloatField()),
                ('branch', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=255)),
                ('fulfillment', models.CharField(blank=True, max_length=255, null=True)),
                ('seat_type', models.CharField(max_length=255)),
                ('primary_seat_type', models.CharField(max_length=255)),
                ('secondary_seat_type', models.CharField(max_length=255)),
                ('score_type', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('enrollment_no', models.CharField(max_length=255)),
                ('branch_code', models.CharField(max_length=255)),
            ],
        ),
    ]
